FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y mosquitto supervisor && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

COPY node/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY node/mosquitto.conf /etc/mosquitto/mosquitto.conf

CMD ["supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]